### ISSUE TITLE
Table.Wrapper

### ISSUE THREAD

**Issue by diegohaz** [diegohaz/reakit#136]
For responsiveness. It should have styles like these:
```
  width: 100%;
  overflow-x: auto;
  -webkit-overflow-scrolling: touch;
```

Usage:

```jsx
<Table.Wrapper>
  <Table>
    ...
  </Table>
</Table.Wrapper>
```

## Instructions:

1. Fork and clone the repository and run `yarn` or `npm install` to install dependencies;

2. Copy a simple component like [`Table`](https://github.com/diegohaz/reakit/blob/master/src/components/Table/Table.js) into `TableWrapper.js` and edit its contents;

3. Create a `TableWrapper.md` file with some example;

4. Assign it to `Table.Wrapper` here: https://github.com/diegohaz/reakit/blob/6c14280f262efe54282d7f2cbf463189c6351103/src/components/Table/index.js#L11-L18

5. Run `npm run website` and open http://localhost:6060/components/table/tablewrapper to see if it's working as you expected;

6. Commit, push and open the PR. 🎉

**Comment by joeynimu** [comment]
@diegohaz I want to work on this if it isn't taken yet :-p

**Comment by diegohaz** [comment]
Sure, @joeynimu. Go ahead. 😊

**Comment by joeynimu** [comment]
@diegohaz when I run `npm run website` I get this error;
```
reakit jngethe$ npm run website

> reakit@0.11.1 website /Users/jngethe/projects/oss/reakit
> styleguidist server

SyntaxError: Unexpected token ...
/Users/jngethe/projects/oss/reakit/styleguide.config.js:41
      ...docs,
      ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at getConfig (/Users/jngethe/projects/oss/reakit/node_modules/react-styleguidist/scripts/config.js:35:12)
```
It's just a `spread` wonder why it throws an error. Let me know if you might know what's the issue as I also look into it.

**Comment by diegohaz** [comment]
That's probably your node version. I think Node v8.6.0 supports spread.

**Comment by joeynimu** [comment]
@diegohaz managed to fix the issue. Question, on which directory should the `TableWrapper.md` go to?

**Comment by diegohaz** [comment]
Awesome. :)

It should be next to `TableWrapper.js` in `src/components/Table`.

**Comment by joeynimu** [comment]
@diegohaz sorry got held up over the weekend with other things. I managed to finish this. One question I have though is, should the wrapper have a `role` as a prop? If yeah, what should it be? Ooh...and some `CI` test are failing :-(

**Comment by joeynimu** [comment]
@diegohaz Kindly have a look, thanks.
#148

**Comment by diegohaz** [comment]
@joeynimu You didn't do anything wrong (probably I did 😅)
Your PR was automatically closed when I pushed my changes to your branch. Please see https://github.com/joeynimu/reakit/pull/1

**Comment by joeynimu** [comment]
@diegohaz haha I see what you mean. I was just curious. I am open to work on the issues /PR's that are within my capability I will have a look at the open issues and run them with you first. Otherwise, thanks.
